nodefault:
	@echo "No default target.";
	@echo "Valid targets: getip, select, apply.";
	@echo "Recommend: Using shell script directly.";

getip: getip.sh
	@chmod +x getip.sh
	./getip.sh

select: select.sh
	@chmod +x select.sh
	./select.sh

apply: apply.sh
	@chmod +x apply.sh
	./apply.sh
